/// <reference types="cypress"/>
import 'cypress-iframe'

describe("Tugas Akhir Eduwork",()=>{
    it("Try to buy product with valid credit card payment method",()=>{
    cy.visit("https://demo.midtrans.com/")
    cy.url().should("include","https://demo.midtrans.com/")
    cy.get('.buy').click()
    cy.get('.cart-checkout').click()
    cy.frameLoaded('#snap-midtrans')
        cy.iframe().contains('Credit/debit card').click()
        cy.iframe().find('.card-number-input-container').type('1234123412341234')
        cy.iframe().find('#card-expiry').type('0228')
        cy.iframe().find('#card-cvv').type('123')
        cy.iframe().find('.card-pay-button-part').click()
    })  
    it("Try to buy product with invalid credit card payment method",()=>{
        cy.visit("https://demo.midtrans.com/")
        cy.url().should("include","https://demo.midtrans.com/")
        cy.get('.buy').click()
        cy.get('.cart-checkout').click()
        cy.frameLoaded('#snap-midtrans')
            cy.iframe().contains('Credit/debit card').click()
            cy.iframe().find('.card-number-input-container').type('1111111111111111')
            cy.iframe().find('#card-expiry').type('0228')
            cy.iframe().find('#card-cvv').type('321')
            cy.iframe().find('.card-pay-button-part').click()
        })  
    it("Try to buy product with bank transfer payment method",()=>{
        cy.visit("https://demo.midtrans.com/")
        cy.url().should("include","https://demo.midtrans.com/")
        cy.get('.buy').click()
        cy.get('.cart-checkout').click()
        cy.frameLoaded('#snap-midtrans')
            cy.iframe().contains('Bank transfer').click()
            cy.iframe().contains('BCA').click()
            cy.iframe().contains('Virtual account number').should('be.visible')
    })
    
    it("Try to buy product with gopay e-wallet payment method",()=>{
        cy.visit("https://demo.midtrans.com/")
        cy.url().should("include","https://demo.midtrans.com/")
        cy.get('.buy').click()
        cy.get('.cart-checkout').click()
        cy.frameLoaded('#snap-midtrans')
            cy.iframe().contains('GoPay/other e-Wallets').click()
            cy.iframe().contains('GoPay').should('be.visible')
    })
    it("Try to buy product with valid kredivo payment method",()=>{
        cy.visit("https://demo.midtrans.com/")
        cy.url().should("include","https://demo.midtrans.com/")
        cy.get('.buy').click()
        cy.get('.cart-checkout').click()
        cy.frameLoaded('#snap-midtrans')
            cy.iframe().contains('Kredivo').click()
            cy.iframe().find('.button-down').click()
        cy.get('#phoneNumber').type('081123123123')
        cy.get('#pin').type('123456')
        cy.contains('Next').click()
        cy.get('#otp').type('1234')
        cy.contains('Next').click()
        cy.contains('Transaction is Successful').should('be.visible')
    })
        it("Try to buy product with invalid kredivo payment method",()=>{
        cy.visit("https://demo.midtrans.com/")
        cy.url().should("include","https://demo.midtrans.com/")
        cy.get('.buy').click()
        cy.get('.cart-checkout').click()
        cy.frameLoaded('#snap-midtrans')
            cy.iframe().contains('Kredivo').click()
            cy.iframe().find('.button-down').click()
        cy.get('#phoneNumber').type('081321321321')
        cy.get('#pin').type('123456')
        cy.contains('Next').click()
        cy.get('#otp').type('1234')
        cy.contains('Next').click()
        cy.contains('Transaction is Denied').should('be.visible')
    })
    it("Try to buy product with alfa group method ",()=>{
        cy.visit("https://demo.midtrans.com/")
        cy.url().should("include","https://demo.midtrans.com/")
        cy.get('.buy').click()
        cy.get('.cart-checkout').click()
        cy.frameLoaded('#snap-midtrans')
            cy.iframe().contains('Alfa Group').click()
            cy.iframe().contains('Alfa Group').should('be.visible')
    })
})

